export type IconName =
  | 'bookmark'
  | 'comment'
  | 'home-stroke'
  | 'home'
  | 'like'
  | 'logo'
  | 'magnifier-stroke-thick'
  | 'magnifier-stroke'
  | 'message-fill'
  | 'message-stroke'
  | 'profile-fill'
  | 'profile-stroke'
  | 'repost'
  | 'share'
  | 'verified-icon'
  | 'view'
