import { Inter } from 'next/font/google'

import { MSWComponent } from '@/components'

import type { Metadata } from 'next'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <MSWComponent />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
